services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  B13\Warmup\:
    resource: '../Classes/*'

  B13\Warmup\Command\WarmupCommand:
    tags:
      - name: console.command
        command: cache:warmupPages
        description: Warms up some basic caches for frontend rendering.

  B13\Warmup\Authentication\FrontendUserGroupInjector:
    tags:
      - name: event.listener
        method: frontendUserGroupModifier
        identifier: b13/warmup/user-group-injector
